### ISSUE TITLE
parseDom (feature request)

### ISSUE THREAD

**Issue by pyhedgehog** [glennjones/microformat-node#20]
Current parseDom operates on jQuery-like objects.
1. Are you planning implementing parser for real DOM API (getElementsByClassName and so on - i.e. [jsdom](https://github.com/tmpvar/jsdom) implements this)?
2. If not - can I volunteer? (no sense to start if you revoke pull request)
3. It yes - what should be function names? (either we should rename old one, or somehow mangle new one)

**Comment by glennjones** [comment]
Hi

Not sure why you would want to do this. Have you got a problem with the current DOM parsing?

The parseDom function structure comes from using https://github.com/cheeriojs/cheerio I picked this parser rather than https://github.com/tmpvar/jsdom because its was noticeable faster and handle more real world web pages without issue. Yes its more jQuery-like (which I do not like), but in tests it works faster with less issues. I think a lot of this is down to it using the more forgiving htmlparser2 code.

I would add that some of the architectural structure of microformat-node is based on a couple of generations of older JavaScript microformat parsers some browser based. So microformat-node could now be refactored into a more terse codebase and use modern JS patterns, but I think thats different from what you are suggesting?

If you could explain a little more what we would gain from the changes I could comment some more.

**Comment by pyhedgehog** [comment]
### Problem 1: (why I want to add support for jsdom):
I already have a project using jsdom and want to add microfomat support.
I can't use cheerio because it doesn't provides DOM API (it's W3C standard at last).
I've not yet hit any page that jsdom can't parse.
I've not really tested parsing speed, but nowadays network still slower than CPU.

### Problem 2: (why I mentioned function names):
Not even [cheerio readme](https://github.com/cheeriojs/cheerio/blob/master/Readme.md) names their API a DOM. DOM means some specific API. So if some function has Dom in it's name somebody like me concludes that it accepts of produces objects that supports this specific API.

If you think that there are too match already-existing code that uses this particular function, I think that something like `parseW3CDOM()` would be clear for user. Is it sounds well for you?

**Comment by pyhedgehog** [comment]
I have an idea - load jQuery using jsdom and pass `window.jQuery` to `parseDom()`. Will this work?

**Comment by glennjones** [comment]
Hi I have rebuilt the library still using cheerio, but is now based on the https://github.com/glennjones/microformat-shiv project. If you want to use `jsdom` I would I inject `microformat-shiv` and use its `get` method. This should work the same as using the current version of this project as they share most of the same code.
