### ISSUE TITLE
Remove or separate out parseUrl() to slim down library?

### ISSUE THREAD

**Issue by voxpelli** [glennjones/microformat-node#24]
I was playing around a bit trying to see if I could get this library working with React Native and got Cheerio and HTMLParser2 working, but for some reason didn't get this module working and that's probably due to the Request module.

When I use `microformat-node` I often do it in a context where I already have URL fetching available. In eg. https://github.com/voxpelli/webpage-webmentions I use `request` myself, but in some newer projects I've started experimenting with other libraries like [node-fetch](https://github.com/bitinn/node-fetch).

I also often do the fetching through something like [fetch-politely](https://github.com/voxpelli/node-fetch-politely) to ensure proper rate-limiting and robots.txt compliance.

All in all – I rarely use the fetching that this library provides, I just use it for parsing the HTML – either directly or by sending it a `cheerio` object. So this module including the entire `request` library is for my use-cases often a bit redundant – and since one can't exclude a dependency it makes it hard to eg. do a slim build for something like React Native where size and complexity might matter more than it does on server side node.js.

So – my proposal would be to either just remove the URL-fetching altogether or to split it up so there's a module that's focused on just the parsing and another that also provides helpers like `parseUrl()`.

What's your thoughts?

**Comment by voxpelli** [comment]
Got it successfully working with React Native after the simplest possible removal: https://github.com/voxpelli/microformat-node/commit/f083572d5aad9cd67a1cc36f830af0f35309b988 (Not suggesting as simple of a removal for the main project, just wanted to try if it actually had an impact)

By then just installing some of the Browserify replacement modules for built in Node ones I could successfully run this module in the iOS JS-runtime that React Native uses.

**Comment by glennjones** [comment]
I have been thinking about creating a wrapping modules for microformat-node. Creating tools that use microformat-node to provide the indieweb authorship discovery etc. I don't want to increase the scope of this project beyond parsing microformats.  I could consider moving URL-fetching over to that type of module.

At the moment I am using `parseUrl()` quite a bit so just remove it without creating a wrapping module would causes quite a lot of duplicated code in my projects.

I have just finished a major update to https://github.com/glennjones/microformat-shiv. Have not used React Native, but did you consider using microformat-shiv rather than a Browserify version of this project?

I now want to align the code in microformat-node and microformat-shiv projects more closely. I am going to set up a dev branch to look at much closer integration. Shiv is getting a bit more love at the moment as Mozilla are getting ready to include it Firefox and FirefoxOS. 

I have an issue that cheerio works well in node.js env, but to get speed in browsers I need the newer W3C DOM 3 features. I would like to support both cheerio,  'jsdom' (as requested in #20) and the browser, but performance demands may mean a more complex solution.

Lots to think about! - I will look at the cross project integration first and deal with modularisation as secondary part of the larger architecture problem.

**Comment by voxpelli** [comment]
I did try `microformat-shiv` but as React Native runs using the iOS javascript runtime, anything that isn't basic javascript or polyfillable by Browserify won't work there, and as there's no DOM within a basic javascript runtime the `microformat-shiv` doesn't work there.

Could one perhaps create adapters to enable support for browsers, `jsdom` as well as `cheerio`?  Have three different ones that sits between the use of DOM-like-methods and the actual DOM/cheerio-methods? Or do you think that would cause too much overhead and/or complexity?

**Comment by glennjones** [comment]
This made sense as I align the APIs for this project and https://github.com/glennjones/microformat-shiv. So the new interface has just a `get` method which you can pass either a HTML string or a Cheerio DOM object.
