### ISSUE TITLE
Dependency "ent" uses deprecated Node punycode module

### ISSUE THREAD

**Issue by andreinwald** [glennjones/microformat-node#46]
This library use abandoned package "ent" that use deprecated Node punycode module.

Temporary solution: https://www.npmjs.com/package/ent-replace

**Comment by voxpelli** [comment]
@andreinwald You're probably better off using https://github.com/microformats/microformats-parser

**Comment by voxpelli** [comment]
@andreinwald Considering that the last update to this module was 7 years ago I doubt it will happen. I myself don't have commit access or publishing rights. You can always fork and publish yourself.

Good thing about https://github.com/microformats/microformats-parser is that its maintained by the community and doesn't rely on any one single maintainer.

**Comment by glennjones** [comment]
@andreinwald Thanks for taking the time to point this out. I have now fully updated all the modules in microformat-node including replacing ent with ent-replace. 

Your request just came in as I am starting to use the module again, hence me picking it up : )

I have not yet run the library against the microformats test suite, there have been about 40 small updates to it since I last went through the process, so the for the now [microformats-parser](https://github.com/microformats/microformats-parser) is more update with the spec. I will sort that out soon.

@voxpelli I did offer transfer this repo over the community many years ago to Tantek, but the conversation got lost in time which is a shame.  I am will bring this back inline for those still using it, mainly me.

**Comment by voxpelli** [comment]
@glennjones I'm still using this library for my webmention endpoint as well 🙂
